export enum EventCode {
  PASSWORD_LOGIN = "PASSWORD_LOGIN",
  OTP_AUTHENTICATION = "OTP_AUTHENTICATION",
  MAGIC_URL_AUTHENTICATION = "MAGIC_URL_AUTHENTICATION",
  LOGOUT = "LOGOUT",
  PASSWORD_RESET = "PASSWORD_RESET",
  USER_VERIFICATION = "USER_VERIFICATION",
  ACCOUNT_CREATION = "ACCOUNT_CREATION",
  ACCOUNT_DELETION = "ACCOUNT_DELETION",
  ACCOUNT_LOCKOUT = "ACCOUNT_LOCKOUT",
  ACCOUNT_UPDATE = "ACCOUNT_UPDATE",
}